In [1]:
import pandas as pd
import numpy as np
import datetime

def transform_to_day(date_string):
    date = date_string.split('-')
    d_list = []
    for d in date:
        d = int(d.split(' ')[0])
        d_list.append(d)
    ans = datetime.date(d_list[0], d_list[1], d_list[2])
    return(ans.strftime("%A"))

In [3]:
month_list = ['April', 'Mei', 'Juni', 'Juli', 'Augustus', 'September', 'Oktober']
file_list = ['./Zettle-Raw-Data-Report-20210401-20210430.xlsx','./Zettle-Raw-Data-Report-20210501-20210531.xlsx','./Zettle-Raw-Data-Report-20210601-20210630.xlsx','./Zettle-Raw-Data-Report-20210701-20210731.xlsx','./Zettle-Raw-Data-Report-20210801-20210831.xlsx','./Zettle-Raw-Data-Report-20210901-20210930.xlsx','./Zettle-Raw-Data-Report-20211001-20211031.xlsx']

df_list = []
for m, f in zip(month_list, file_list):
    month_df = pd.read_excel(f, header=5)
    month_df['Maand'] = m
    totaal = np.sum(month_df['Uiteindelijke prijs (EUR)'])
    month_df['Totaal bedrag maand'] = totaal
    month_df['Dag'] = month_df.apply(lambda row: transform_to_day(str(row['Datum'])), axis = 1)
    for d in month_df['Dag'].unique():
        day_df = month_df[month_df['Dag'] == d]
        day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
        df_list.append(day_df)

df = pd.concat(df_list)

/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/home/dirk/miniconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])
/tmp/ipykernel_27498/1850257313.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_df['Totaal bedrag dag'] = np.sum(day_df['Uiteindelijke prijs (EUR)'])

In [4]:
print(len(df))
df

4453

,Datum,Tijd,Personeel,Bonnummer,Product,Variant,Eenheid,Aantal,Prijs (EUR),Korting (EUR),Uiteindelijke prijs (EUR),SKU,Barcode,Kostprijs,Opmerking,Maand,Totaal bedrag maand,Dag,Totaal bedrag dag
0,2021-04-02 10:02:48.076,2021-04-02 10:02:48.076,Noor Schuit,1338.0,NaN,NaN,NaN,1.0,50.0,0.0,50.0,NaN,NaN,0.0,NaN,April,2413.5,Friday,254.0
1,2021-04-02 10:02:48.076,2021-04-02 10:02:48.076,Noor Schuit,1338.0,Fooien,NaN,NaN,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,April,2413.5,Friday,254.0
2,2021-04-02 13:34:10.049,2021-04-02 13:34:10.049,Noor Schuit,1339.0,NaN,NaN,NaN,1.0,37.5,0.0,37.5,NaN,NaN,0.0,NaN,April,2413.5,Friday,254.0
3,2021-04-02 13:34:10.049,2021-04-02 13:34:10.049,Noor Schuit,1339.0,Fooien,NaN,NaN,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,April,2413.5,Friday,254.0
75,2021-04-09 16:46:46.718,2021-04-09 16:46:46.718,Noor Schuit,1377.0,NaN,NaN,NaN,1.0,35.0,0.0,35.0,NaN,NaN,0.0,NaN,April,2413.5,Friday,254.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2021-10-04 16:51:08.292,2021-10-04 16:51:08.292,Noor Schuit,2620.0,high tea,NaN,NaN,1.0,25.0,0.0,25.0,NaN,NaN,0.0,NaN,Oktober,843.5,Monday,288.0
110,2021-10-04 16:51:08.292,2021-10-04 16:51:08.292,Noor Schuit,2620.0,koffie,NaN,NaN,1.0,2.5,0.0,2.5,NaN,NaN,0.0,NaN,Oktober,843.5,Monday,288.0
111,2021-10-04 16:51:08.292,2021-10-04 16:51:08.292,Noor Schuit,2620.0,Fooien,NaN,NaN,1.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,Oktober,843.5,Monday,288.0
112,2021-10-04 16:52:41.010,2021-10-04 16:52:41.010,Noor Schuit,2621.0,high tea,NaN,NaN,2.0,50.0,0.0,50.0,NaN,NaN,0.0,NaN,Oktober,843.5,Monday,288.0
113,2021-10-04 16:52:41.010,2021-10-04 16:52:41.010,Noor Schuit,2621.0,koffie,NaN,NaN,2.0,5.0,0.0,5.0,NaN,NaN,0.0,NaN,Oktober,843.5,Monday,288.0

In [4]:
print(df['Product'].unique())

[nan 'Fooien' 'Kaart' 'punt appeltaart' 'taart van de dag' 'cappuccino'
 'aanmaak limonade' 'slagroom' 'koffie' 'dubbele koffie' 'exota'
 'latte macchiato' 'zakje losse thee' 'drip koffie' 'kop thee'
 'huisgemaakte ice tea' 'espresso' 'exota groot' 'spa blauw/spa rood'
 'pot thee voor 2' 'dubbele espresso' 'kan ranja' 'lp klok ravenstein'
 'zonnebrilkoord' 'thee bloem voor 2' 'enkelbandje' 'ketting ' 'taart'
 'Bert en Ernie' 'door verkoop' 'blondie' 'huisje' 'gevilte slof'
 'cadeaubon' 'bonsai bakje' 'macarons' 'kastje' 'slofjes' 'Puck kopjes'
 'ragout kopje' 'giraffe' 'lp onderzetters 10x' 'muts' 'lp klok'
 '1 thee bloem' 'ring' 'taart ' '4 theebloemen' 'salamander' 'cadeau bon'
 'high tea' 'wandelstok' 'rompertje' 'appeltaarten' 'paard' 'vaas' 'wijer'
 'spin' 'klok' 'bezem' 'plantenhanger' 'bestelling' 'macramé' 'flesje'
 'flesjes' 'lepels' 'blik' 'tafelkleed hangers']

In [5]:
def transform_to_day(date_string):
    date = date_string.split('-')
    d_list = []
    for d in date:
        d = int(d.split(' ')[0])
        d_list.append(d)

    import datetime
    ans = datetime.date(d_list[0], d_list[1], d_list[2])
    return(ans.strftime("%A"))

In [5]:
df.to_csv('Nono.csv')

In [15]:
from collections import defaultdict
result_dict_list = []
for maand in df['Maand'].unique():
    maand_df = df[df['Maand'] == maand]
    for product in maand_df['Product'].unique():
        product_df = maand_df[maand_df['Product'] == product]
        product_sum = np.sum(product_df['Uiteindelijke prijs (EUR)'])
        result_dict = {}
        result_dict['Maand'] = maand
        result_dict['Product'] = product
        result_dict['Euros'] = product_sum
        result_dict_list.append(result_dict)


product_df = pd.DataFrame(result_dict_list)

In [21]:
product_df.to_csv('product.csv')

In [19]:
product_df

       Maand           Product  Euros
0      April               NaN    0.0
1      April            Fooien    2.5
2      April             Kaart    1.5
3        Mei               NaN    0.0
4        Mei            Fooien   32.5
..       ...               ...    ...
189  Oktober          high tea  375.0
190  Oktober             exota    2.5
191  Oktober    dubbele koffie    4.0
192  Oktober  zakje losse thee    6.0
193  Oktober       drip koffie    3.0

[194 rows x 3 columns]